import { createRouter, createWebHistory, type RouteRecordRaw } from 'vue-router'
import { setupGuard } from './guard'

const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/login/index.vue'),
    meta: { public: true },
  },
  {
    path: '/',
    component: () => import('@/layouts/BasicLayout.vue'),
    redirect: '/dashboard',
    children: [
      {
        path: 'dashboard',
        name: 'Dashboard',
        component: () => import('@/views/dashboard/index.vue'),
        meta: { title: '工作台' },
      },
      {
        path: 'workbench/tasks',
        name: 'TaskCenter',
        component: () => import('@/views/workbench/TaskCenter.vue'),
        meta: { title: '个人任务中心' },
      },
      {
        path: 'workbench/messages',
        name: 'MessageCenter',
        component: () => import('@/views/workbench/MessageCenter.vue'),
        meta: { title: '消息中心' },
      },
      { path: 'kpi/compare',
        name: 'KpiCompare',
        component: () => import('@/views/kpi/KpiCompare.vue'),
        meta: { title: '分公司 KPI 对比', perm: 'system.org.switch' } },
      { path: 'fia', redirect: '/fia/tasks' },
      { path: 'fia/tasks', name: 'FiaTasks', component: () => import('@/views/fia/TaskList.vue'), meta: { title: '首件检验' } },
      { path: 'fia/tasks/create', name: 'FiaTaskCreate', component: () => import('@/views/fia/TaskCreate.vue'), meta: { title: '新建任务' } },
      { path: 'fia/tasks/:id', name: 'FiaTaskDetail', component: () => import('@/views/fia/TaskDetail.vue'), meta: { title: '任务详情' } },
      { path: 'fia/approvals', name: 'FiaApprovals', component: () => import('@/views/fia/ApprovalList.vue'), meta: { title: '审批单' } },
      { path: 'fia/stds', name: 'FiaStds', component: () => import('@/views/fia/StdList.vue'), meta: { title: '检验标准' } },
      { path: 'fia/std-items', name: 'FiaStdItems', component: () => import('@/views/fia/StdItemMaintain.vue'), meta: { title: '检验项明细维护' } },
      { path: 'fia/triggers', name: 'FiaTriggers', component: () => import('@/views/fia/TriggerList.vue'), meta: { title: '触发类型' } },
      { path: 'fia/wo-lock', name: 'FiaWoLock', component: () => import('@/views/fia/WoLockList.vue'), meta: { title: '工单锁定' } },
      { path: 'fia/incoming', name: 'FiaIncoming', component: () => import('@/views/fia/IncomingList.vue'), meta: { title: '来料检验' } },
      { path: 'fia/incoming/:id', name: 'FiaIncomingDetail', component: () => import('@/views/fia/IncomingDetail.vue'), meta: { title: '来料检验详情' } },
      { path: 'spc', redirect: '/spc/params' },
      { path: 'spc/params', name: 'SpcParams', component: () => import('@/views/spc/ParamList.vue'), meta: { title: 'SPC参数' } },
      { path: 'spc/processes', name: 'SpcProcesses', component: () => import('@/views/spc/ProcessList.vue'), meta: { title: 'SPC工序管理' } },
      { path: 'spc/spec-standards', name: 'SpcSpecStandards', component: () => import('@/views/spc/SpecStandard.vue'), meta: { title: '标准线管理' } },
      { path: 'spc/params/:id', name: 'SpcChart', component: () => import('@/views/spc/ChartView.vue'), meta: { title: '控制图' } },
      { path: 'spc/collect', name: 'SpcCollect', component: () => import('@/views/spc/CollectView.vue'), meta: { title: '数据采集' } },
      { path: 'spc/sample-tasks', name: 'SpcSampleTaskCreate', component: () => import('@/views/spc/SampleTaskCreate.vue'), meta: { title: '抽样任务创建' } },
      { path: 'spc/sample-collect/:taskId', name: 'SpcSampleCollect', component: () => import('@/views/spc/SampleCollect.vue'), meta: { title: '抽样采集' } },
      { path: 'spc/collect-tasks', name: 'SpcCollectTasks', component: () => import('@/views/spc/CollectTask.vue'), meta: { title: '采集任务管理' } },
      { path: 'spc/alarms', name: 'SpcAlarms', component: () => import('@/views/spc/AlarmList.vue'), meta: { title: 'SPC告警' } },
      { path: 'spc/capability', name: 'SpcCapability', component: () => import('@/views/spc/Capability.vue'), meta: { title: 'SPC能力分析' } },
      { path: 'spc/rules', name: 'SpcRules', component: () => import('@/views/spc/RuleDetection.vue'), meta: { title: 'SPC判异规则' } },
      { path: 'ncm', name: 'NcmIndex', component: () => import('@/views/ncm/NcmIndex.vue'), meta: { title: '不良管理' } },
      { path: 'ncm/defect-dicts', name: 'NcmDefectDicts', component: () => import('@/views/ncm/DefectDictList.vue'), meta: { title: '不良字典' } },
      { path: 'ncm/defect-records', name: 'NcmDefectRecords', component: () => import('@/views/ncm/DefectRecordList.vue'), meta: { title: '不良记录' } },
      { path: 'ncm/8d-reports', name: 'Ncm8dList', component: () => import('@/views/ncm/8dList.vue'), meta: { title: '8D报告' } },
      { path: 'ncm/8d-reports/:id', name: 'Ncm8dDetail', component: () => import('@/views/ncm/8dDetail.vue'), meta: { title: '8D详情' } },
      { path: 'ncm/8d-approval-config', redirect: '/system/audit-config' },
      { path: 'ncm/capas', name: 'NcmCapas', component: () => import('@/views/ncm/CapaList.vue'), meta: { title: 'CAPA' } },
      { path: 'ncm/capas/:id', name: 'NcmCapaDetail', component: () => import('@/views/ncm/CapaDetail.vue'), meta: { title: 'CAPA详情' } },
      { path: 'ncm/trend-reports', name: 'NcmTrendReports', component: () => import('@/views/ncm/TrendReport.vue'), meta: { title: '不良趋势报表' } },
      { path: 'ncm/corrective-actions', name: 'NcmCorrectiveActions', component: () => import('@/views/ncm/CorrectiveActionList.vue'), meta: { title: '纠正措施' } },
      { path: 'ncm/corrective-actions/:id', name: 'NcmCorrectiveActionDetail', component: () => import('@/views/ncm/CorrectiveActionDetail.vue'), meta: { title: '纠正措施详情' } },
      { path: 'ncm/defect-records/:id', name: 'NcmDefectRecordDetail', component: () => import('@/views/ncm/DefectRecordDetail.vue'), meta: { title: '不良记录详情' } },
      { path: 'sqm', name: 'SqmIndex', component: () => import('@/views/sqm/SupplierList.vue'), meta: { title: '供应商' } },
      { path: 'sqm/suppliers', name: 'SqmSuppliers', component: () => import('@/views/sqm/SupplierList.vue'), meta: { title: '供应商' } },
      { path: 'sqm/abnormals', name: 'SqmAbnormals', component: () => import('@/views/sqm/AbnormalList.vue'), meta: { title: '来料异常' } },
      { path: 'sqm/audits', name: 'SqmAudits', component: () => import('@/views/sqm/AuditList.vue'), meta: { title: '审核' } },
      { path: 'sqm/audits/execute/:planId', name: 'SqmAuditExecute', component: () => import('@/views/sqm/AuditExecute.vue'), meta: { title: '审核执行' } },
      { path: 'sqm/audits/record/:recordId', name: 'SqmAuditRecord', component: () => import('@/views/sqm/AuditRecordDetail.vue'), meta: { title: '审核记录' } },
      { path: 'system/audit-config', name: 'SqmAuditConfig', component: () => import('@/views/sqm/AuditApprovalConfig.vue'), meta: { title: '审核人员配置' } },
      { path: 'sqm/changes', name: 'SqmChanges', component: () => import('@/views/sqm/ChangeList.vue'), meta: { title: '变更' } },
      { path: 'sqm/supplier-lots', name: 'SqmSupplierLots', component: () => import('@/views/sqm/SupplierLots.vue'), meta: { title: '供应商来料批次' } },
      { path: 'sqm/trace', name: 'SqmTrace', component: () => import('@/views/sqm/TraceList.vue'), meta: { title: '物料追溯' } },
      { path: 'sqm/trace/view', redirect: '/sqm/trace' },
      { path: 'sqm/trace/mes-view', name: 'SqmMesTraceView', component: () => import('@/views/sqm/MesTraceView.vue'), meta: { title: 'MES追溯(源表+关系表)' } },
      { path: 'sqm/trace/tree', redirect: '/sqm/trace' },
      { path: 'sqm/performance', name: 'SqmPerformance', component: () => import('@/views/sqm/PerformanceList.vue'), meta: { title: '供应商绩效' } },
      { path: 'sqm/perf-config', name: 'SqmPerfConfig', component: () => import('@/views/sqm/PerfConfig.vue'), meta: { title: '绩效指标配置' } },
      { path: 'sqm/dashboard', name: 'SqmDashboard', component: () => import('@/views/sqm/SqmDashboard.vue'), meta: { title: '供应商质量看板' } },
      { path: 'sqm/fmea', name: 'SqmFmea', component: () => import('@/views/sqm/FmeaList.vue'), meta: { title: 'FMEA风险管控' } },
      { path: 'patrol', redirect: '/patrol/routes' },
      { path: 'patrol/routes', name: 'PatlRoutes', component: () => import('@/views/patrol/RouteList.vue'), meta: { title: '巡检路线' } },
      { path: 'patrol/tasks', name: 'PatlTasks', component: () => import('@/views/patrol/TaskList.vue'), meta: { title: '巡检任务' } },
      { path: 'patrol/abnormals', name: 'PatlAbnormals', component: () => import('@/views/patrol/AbnormalList.vue'), meta: { title: '巡检异常' } },
      { path: 'tlm', redirect: '/tlm/tooling' },
      { path: 'tlm/tooling', name: 'TlmTooling', component: () => import('@/views/tlm/ToolingList.vue'), meta: { title: '工装台账' } },
      { path: 'tlm/tooling/:id', name: 'TlmToolingDetail', component: () => import('@/views/tlm/ToolingDetail.vue'), meta: { title: '工装详情' } },
      { path: 'tlm/maint', name: 'TlmMaint', component: () => import('@/views/tlm/MaintList.vue'), meta: { title: '工装维保' } },
      { path: 'tlm/abnormals', name: 'TlmAbnormals', component: () => import('@/views/tlm/AbnormalList.vue'), meta: { title: '工装异常' } },
      { path: 'tlm/repairs', name: 'TlmRepairs', component: () => import('@/views/tlm/RepairList.vue'), meta: { title: '维修工单' } },
      { path: 'tlm/scraps', name: 'TlmScraps', component: () => import('@/views/tlm/ScrapList.vue'), meta: { title: '报废管理' } },
      { path: 'tlm/metro', name: 'TlmMetro', component: () => import('@/views/tlm/MetroList.vue'), meta: { title: '计量管理' } },
      { path: 'tlm/metro/plans', name: 'TlmMetroPlans', component: () => import('@/views/tlm/MetroCalibPlan.vue'), meta: { title: '校准计划' } },
      { path: 'tlm/metro/:id', name: 'TlmMetroDetail', component: () => import('@/views/tlm/ToolingDetail.vue'), meta: { title: '计量器具详情' } },
      { path: 'archive', redirect: '/archive/list' },
      { path: 'archive/list', name: 'ArchiveList', component: () => import('@/views/archive/ArchiveList.vue'), meta: { title: '归档查询' } },
      { path: 'system', redirect: '/system/users' },
      { path: 'system/users', name: 'SystemUsers', component: () => import('@/views/system/UserList.vue'), meta: { title: '用户管理' } },
      { path: 'system/roles', name: 'SystemRoles', component: () => import('@/views/system/RoleList.vue'), meta: { title: '角色管理' } },
      { path: 'system/roles/:id/perm', name: 'SystemRolePermission', component: () => import('@/views/system/RolePermission.vue'), meta: { title: '权限配置' } },
      { path: 'system/orgs', name: 'SystemOrgs', component: () => import('@/views/system/OrgView.vue'), meta: { title: '组织管理' } },
      { path: 'system/menus', name: 'SystemMenus', component: () => import('@/views/system/MenuList.vue'), meta: { title: '菜单管理' } },
      { path: 'system/notify-config', name: 'SystemNotifyConfig', component: () => import('@/views/system/NotifyConfig.vue'), meta: { title: '通知配置' } },
      { path: 'system/notify-center', name: 'SystemNotifyCenter', component: () => import('@/views/system/NotifyCenter.vue'), meta: { title: '通知中心' } },
      { path: 'system/abnormal-rule', name: 'SystemAbnormalRule', component: () => import('@/views/system/AbnormalRuleConfig.vue'), meta: { title: '异常严重度规则' } },
      { path: 'system/audit-logs', name: 'SystemAuditLogs', component: () => import('@/views/system/AuditLogList.vue'), meta: { title: '审计日志' } },
    ],
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    component: () => import('@/views/404.vue'),
    meta: { public: true },
  },
]

const router = createRouter({
  history: createWebHistory(),
  routes,
})

setupGuard(router)

export default router
